### ISSUE TITLE
[FE: FEATURE] Main - PlaylistCreator Merge

### ISSUE THREAD

**Issue by yuwon707** [codestates-seb/seb42_main_024#112]
## 📋 이슈 내용

- 메인페이지에 PlaylistCreator 컴포넌트 병합

## 📝 상세 내용

- 메인페이지에서 플레이리스트 생성
- 생성한 플레이리스트로 메인페이지 렌더링

## ✔️ To-do

- [x] 플레이리스트 생성
  - [x] 제목, 설명글 작성
  - [x] 원하는 음악 검색
  - [x] 음악 추가, 삭제
- [x] 원하는 리스트를 사용하여 Trendy 렌더링 구현
- [x] 원하는 리스트를 사용하여 Slider 렌더링 구현

## 🤔 필요 데이터

- /api/boards

## ✍🏻 데이터스키마

```
"memberId": 0,
"boardContent": "string",
"boardTitle": "string",
"playlistId": 0,
"boardThumb": "string",
"playlist": {
  "title": "string",
  "songList": [
    {
      "videoId": "string",
      "title": "string",
      "thumbnail": "string"
    }
  ]
```
