### ISSUE TITLE
[FE: FEATURE] Nav 컴포넌트 구현

### ISSUE THREAD

**Issue by yuwon707** [codestates-seb/seb42_main_024#22]
## 📋 이슈 내용
- Nav 컴포넌트를 구현한다

## 📝 상세 내용
- 메뉴 별 이동
- 로그인/로그아웃
- 플레이리스트 생성

## ✔️ To-do
- [x] 로그인/로그아웃 상태별 메뉴 구현
- [x] google 로그인/로그아웃 기능 구현
- [x] 페이지 이동 구현

## 🤔 필요 데이터
- 로그인 정보(google 로그인)

## ✍🏻 데이터스키마
```

```
