### ISSUE TITLE
[FE: FEATURE] NowPlaying 컴포넌트 구현

### ISSUE THREAD

**Issue by yuwon707** [codestates-seb/seb42_main_024#23]
## 📋 이슈 내용
- NowPlaying 컴포넌트를 구현한다

## 📝 상세 내용
- 현재 재생 중인 곡의 정보 확인
- 재생/정지, 이전 곡/다음 곡 이동

## ✔️ To-do
- [ ] 데이터 스키마 작성
- [ ] 재생/정지 기능 구현
- [ ] 이전 곡/다음 곡 이동 기능 구현
- [ ] 재생 중인 곡 정보 확인

## 🤔 필요 데이터
- 플레이리스트 제목
- 곡 제목
- 아티스트
- 현재 재생 시간
- 총 재생 시간

## ✍🏻 데이터스키마
```
playListTitle: string,
musicTitle: string,
artist: string,
playTime: date,
totalPlayTime: date
```
