### ISSUE TITLE
[FE: FEATURE] PlayList 컴포넌트 구현

### ISSUE THREAD

**Issue by yuwon707** [codestates-seb/seb42_main_024#24]
## 📋 이슈 내용
- PlayList 컴포넌트 구현

## 📝 상세 내용
- 특정 플레이리스트의 썸네일, 제목, 재생 시간, 작성자, 음악 목록을 확인할 수 있다
- MainPage, PlaylistPage의 플레이리스트 컴포넌트 구현

## ✔️ To-do
- [x] Playlist 페이지 - PlaylistInfo 컴포넌트 구현
- [x] Playlist 페이지 - PlaylistList 컴포넌트 구현
- [x] Main 페이지 - PlaylistTrendy 컴포넌트 구현
- [x] Main 페이지 - PlaylistThumbnail 컴포넌트 구현

## 🤔 필요 데이터
- 플레이리스트 제목
- 플레이리스트 설명
- 플레이리스트 썸네일
- 플레이리스트 총 재생 시간
- 플레이리스트 총 곡 수
- 곡 제목
- 아티스트
- 앨범
- 재생 시간

## ✍🏻 데이터스키마
```
playListTitle: string,
playListBody: string,
thumbnail: string,
totalPlayTime: date,
totalCount: number,
musicTitle: string,
artist: string,
album: string,
playTime: date
```

## 컴포넌트 별 구조
1. Playlist 페이지 - PlaylistInfo 컴포넌트
2. Playlist 페이지 - PlaylistList 컴포넌트
3. Main 페이지 - PlaylistTrendy 컴포넌트
4. Main 페이지 - PlaylistThumbnail 컴포넌트

![playlist components (2)](https://user-images.githubusercontent.com/81921470/225222747-4c48ad29-b245-416d-a87d-345769632f45.png)

## 더미데이터 -> JSON server 사용
db.json

```js
{
  "data": [
    {
      "id": 1,
      "title": "NewJeans",
      "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
      "description": "레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹레트로한 분위기, 자연스러운 매력으로 K-POP의 새로운 신드롬을 예고하는 걸 그룹",
      "totalPlayTime": "25:12",
      "playlist": [
        {
          "id": 1,
          "title": "OMG",
          "artist": "NewJeans",
          "youtubeKey": "sVTy_wmn5SU",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "3:32"
        },
        {
          "id": 2,
          "title": "Ditto",
          "artist": "NewJeans",
          "youtubeKey": "Km71Rr9K-Bw",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "3:06"
        },
        {
          "id": 3,
          "title": "Attention",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "3:00"
        },
        {
          "id": 4,
          "title": "Hype Boy",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "2:59"
        },
        {
          "id": 5,
          "title": "Cookie",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "3:56"
        },
        {
          "id": 6,
          "title": "Hurt",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "2:58"
        },
        {
          "id": 7,
          "title": "?",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "2:58"
        },
        {
          "id": 8,
          "title": "??",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "2:58"
        },
        {
          "id": 9,
          "title": "???",
          "artist": "NewJeans",
          "src": "",
          "imgSrc": "https://cdnimg.melon.co.kr/cm2/album/images/110/11/565/11011565_20220801102637_500.jpg?1d674a44faffa0ebd34d86c182463171/melon/resize/282/quality/80/optimize",
          "playtime": "2:58"
        }
      ]
    },
    {
      "id": 2,
      "title": "요즘 많이 듣는 노래",
      "imgSrc": "",
      "description": "요즘 많이 듣는 노래 설명",
      "totalPlayTime": "9:51",
      "playlist": [
        {
          "id": 1,
          "title": "Don't Need You",
          "artist": "Genesis Owusu",
          "youtubeKey": "FNhWP8qPVbY",
          "imgSrc": "https://img.apmcdn.org/6a1fa84439b8c0d26e5cbf8a256d64365ddae723/square/b8895b-20211217-genesis-owusu-smiling-with-no-teeth-cover-600.jpg",
          "playtime": "3:05"
        },
        {
          "id": 2,
          "title": "On and On",
          "artist": "Lars Eriksson",
          "youtubeKey": "-vFjqF5XSIY",
          "imgSrc": "https://i.ytimg.com/vi/zYNfD9WDYlY/maxresdefault.jpg",
          "playtime": "4:05"
        },
        {
          "id": 3,
          "title": "나의 모든 이들에게,",
          "artist": "밍기뉴",
          "youtubeKey": "Y18kY_HWFAE",
          "imgSrc": "https://image.bugsm.co.kr/album/images/500/205370/20537040.jpg",
          "playtime": "2:41"
        }
      ]
    }
  ]
}
```
