### ISSUE TITLE
[FE: FEATURE] SearchBar 컴포넌트 구현

### ISSUE THREAD

**Issue by yuwon707** [codestates-seb/seb42_main_024#36]
## 📋 이슈 내용
- 통합 검색 SearchBar 컴포넌트 구현

## 📝 상세 내용
- 플레이리스트 검색
- 특정 곡이 포함된 플레이리스트 검색
- 유저 검색

## ✔️ To-do
- [ ] 플레이리스트 검색 기능 구현
- [ ] 특정 곡이 포함된 플레이리스트 검색 기능 구현
- [ ] (option) 유저 검색 기능 구현

## 🤔 필요 데이터
- 플레이리스트 제목
- 플레이리스트 썸네일
- 플레이리스트에 포함된 곡의 제목
- 플레이리스트에 포함된 곡의 아티스트
- (option) 유저 닉네임

## ✍🏻 데이터스키마
```
playListTitle: string,
thumbnail: string,
musicTitle: string,
artist: string,
userName: string
```
